export const ACTION_TYPES = {
  workspaceShell: {
    setRee: "workspaceShell/setRee",
    setLocked: "workspaceShell/setLocked",
    setRepoMode: "workspaceShell/setRepoMode",
    setActionStates: "workspaceShell/setActionStates",
    setBadges: "workspaceShell/setBadges",
    setTimestamps: "workspaceShell/setTimestamps",
    setWorkflowLogs: "workspaceShell/setWorkflowLogs",
    setWorkflowParams: "workspaceShell/setWorkflowParams",
    setToast: "workspaceShell/setToast",
    setPage: "workspaceShell/setPage",
    setFocusedField: "workspaceShell/setFocusedField",
    setNavCollapsed: "workspaceShell/setNavCollapsed",
    setWorkspaceFiles: "workspaceShell/setWorkspaceFiles",
    setReeArtifactFiles: "workspaceShell/setReeArtifactFiles",
    hydrateWorkspace: "workspaceShell/hydrateWorkspace",
    setSourceSnapshotFiles: "workspaceShell/setSourceSnapshotFiles",
    setSourceSnapshotArchiveName: "workspaceShell/setSourceSnapshotArchiveName",
    applySourcePatchOutcome: "workspaceShell/applySourcePatchOutcome",
    setShowReviewPreview: "workspaceShell/setShowReviewPreview",
    completeWorkflowRun: "workspaceShell/completeWorkflowRun",
    resetWorkflowOnSourceChange: "workspaceShell/resetWorkflowOnSourceChange",
  },
} as const;
