interface FieldMeta {
  label: string;
  desc: string;
  example?: string;
  format?: string;
  howTo?: string;
  tools?: Array<{ label: string; url: string }>;
  toolCommands?: Array<{ label: string; cmd: string }>;
}

export const FIELD_META: Record<string, FieldMeta> = {
  name: {
    label: "Name",
    desc: "A human-readable identifier for this REE.",
    example: "climate-model-v2.1.0",
    format: "Lowercase, hyphens allowed. Include a version suffix.",
    howTo:
      "Choose a name that reflects the project and version. This will appear in manifests and citations.",
    tools: [],
  },
  hardware_description: {
    label: "Hardware BOM",
    desc: "Manual hardware bill of materials for the machine or target environment used by this REE.",
    example: "cpu: AMD EPYC, memory: 64 GB, gpu: NVIDIA A100, os: Ubuntu 24.04",
    format: "Key/value pairs such as cpu, memory, gpu, storage, network, os, or accelerator.",
    howTo:
      "Add the machine details that most affect reproducibility today. This is manual for now and can later be sourced from local or remote machines.",
    tools: [],
  },
  swhid: {
    label: "SWHID",
    desc: "Permanent Software Heritage identifier. Auto-assigned when you run Archive.",
    example: "swh:1:dir:4b825dc642cb6eb9a060e54bf8d69288fbee4904",
    format: "swh:1:<type>:<sha1hex> — assigned by Software Heritage on deposit.",
    howTo:
      "You don't fill this manually. Run the Archive service and it will be assigned automatically.",
    tools: [],
  },
  origin_url: {
    label: "Origin URL",
    desc: "URL of the remote software origin or tarball download (optional if you upload locally).",
    example: "https://github.com/org/climate-model",
    format: "Use the clone/checkout URL provided by the host, or a direct tarball URL.",
    howTo:
      "To avoid archiving errors, use the provider clone URL and verify it works before submission (for example, `git clone <origin_url>` for git origins).",
    tools: [
      { label: "GitHub", url: "https://github.com" },
      { label: "GitLab", url: "https://gitlab.com" },
    ],
  },
  _sourceAcquiredBy: {
    label: "Origin Provisioning Status",
    desc: "How source files were provided to the workspace.",
    example: "Uploaded archive",
    format: "Automatically set after source acquisition.",
    howTo: "Set automatically based on whether source came from origin download or local upload.",
    tools: [],
  },
  source_type: {
    label: "Origin Type",
    desc: "Type of software origin used for Save Code Now style archiving.",
    example: "git",
    format:
      "One of: git, hg, svn, cvs, bzr, tarball. Tarball formats include: .jar, .tar, .tar.bz2, .tar.gz, .tar.lz, .tar.xz, .tar.zst, .zip.",
    howTo:
      "Use the clone/checkout URL from the provider UI, and verify it works (for example, `git clone <origin_url>` for git) before requesting download.",
    tools: [],
  },
  _sourceAvailable: {
    label: "In Workspace",
    desc: "Whether the repository has been materialized into the local workspace.",
    example: "Yes — repository is available in workspace",
    format: "Set automatically after source download or tarball upload.",
    howTo:
      "Download from origin or upload a tarball to populate the workspace before Evaluate/Build.",
    tools: [],
  },
  detected_dependencies: {
    label: "Detected Dependencies",
    desc: "See what dependencies were found in your project files. Technically, Evaluate scans manifests in the workspace and summarizes detected packages.",
    example: "24 dependencies across 3 manifest files",
    format: "Auto-generated by Evaluate after a successful run.",
    howTo:
      "Run Evaluate after loading source. The scanner inspects requirements.txt, pyproject.toml, environment.yml, and package.json when present.",
    tools: [],
  },
  repro_level: {
    label: "Repro Level",
    desc: "See your current reproducibility maturity at a glance. Technically, Evaluate computes this level from repository metadata and dependency/runtime signals.",
    example: "L4 · Dependencies Locked",
    format: "Auto-generated by Evaluate after a successful run.",
    howTo:
      "Run Evaluate to compute this value from available repository metadata and detected dependency/runtime signals.",
    tools: [],
  },
  runtime: {
    label: "Runtime",
    desc: "Specify the exact runtime artifact used for verification and packaging. Technically, this is either a bundled .tar.gz tarball or a container image reference used as the SBOM scan target.",
    example: "runtime.tar.gz  or  ree:latest",
    format:
      "A .tar.gz path (bundled) or a Docker/Podman image ref (not bundled). Set before running Build Runtime.",
    howTo: `Set this to whatever your build script produces. Two options:

Tarball (included in REE archive):
  docker save ree:latest | gzip > runtime.tar.gz
  → set runtime = "runtime.tar.gz"

Image ref (not bundled, rebuilt from script):
  docker build -t ree:latest .
  → set runtime = "ree:latest"

The SBOM step reads this field to know what to hand to syft.`,
    tools: [],
  },
  build_runtime_script: {
    label: "Build script",
    desc: "Define how to create the runtime in a repeatable way. Technically, Build Runtime executes this script to produce the artifact referenced by runtime.",
    example: "scripts/build_runtime.sh",
    format: "A shell script (.sh) relative to repo root. Must be executable.",
    howTo: `Create a script that builds your environment deterministically. The script should produce whatever is set as the runtime field. Example:

#!/bin/bash
set -euo pipefail
DOCKER_BUILDKIT=1 docker build --no-cache -t ree:latest .
docker save ree:latest | gzip > runtime.tar.gz`,
    tools: [],
  },
  activation_script: {
    label: "Activation script",
    desc: "Define a quick check that proves the runtime can actually start. Technically, this script loads the runtime and exits successfully only if activation passes.",
    example: "scripts/activation_test.sh",
    format: "A shell script (.sh) relative to repo root. Should exit 0 if the container starts.",
    howTo: `Create a script that loads the runtime tarball and runs a minimal startup check. Example:

#!/bin/bash
set -euo pipefail
docker load < runtime.tar.gz
docker run --rm --entrypoint="" ree:latest echo ok`,
    tools: [],
  },
  sbom: {
    label: "SBOM",
    desc: "Stores the generated inventory file of software in your runtime. Technically, this field is auto-populated with the SPDX 2.3 SBOM output from Generate SBOM.",
    example: "sbom.json",
    format: "SPDX 2.3 JSON. Generated automatically — assigned only after running Generate SBOM.",
    howTo:
      "Go to the Generate SBOM step and click Run after your runtime is ready. The SBOM file is produced and the sbom field is set automatically.",
    tools: [],
    toolCommands: [],
  },
};
