"""Shell renderer for the pip-requirements build strategy.

The runtime for a plain requirements.txt repository is a Python virtual
environment, not a container: the build script creates a venv, installs
requirements.txt into it with pip, and packs the venv as the runtime artifact.
It introduces no technology the repository did not already declare — no
Dockerfile, no base image, no second file. This mirrors the docker-less flow the
e2e suite exercises (``ree-pip-pipeline``), where the workbench base image *is*
the environment and every runnable restores this packed venv instead of loading
an image.

The venv is built outside the workspace (``VENV_DIR``): the workspace is
snapshot-hashed on every change, so a multi-thousand-file venv inside it would
slow every edit, and a venv bakes absolute paths so it must be restored where it
was built. Only the packed tarball — one workspace file — is the tracked
artifact.
"""

from __future__ import annotations

from repo2ree_core.script_inference.models import (
    DEFAULT_VENV_RESTORE_DIR,
    BindingKind,
    CandidateDependency,
    DecisionContext,
    InferenceEvidence,
    ProjectRootBinding,
    RenderedScript,
    RequirementsProjectBinding,
    ScriptTarget,
)
from repo2ree_core.script_inference.renderers._common import (
    VENV_RUNTIME_ARTIFACT_SUFFIX,
    runtime_artifact_path,
    sh_comment,
    sh_quote,
)
from repo2ree_core.script_inference.warnings import make_warning

# Where the venv is built inside the bench — deliberately outside the workspace
# (see module docstring). Shared with the run scaffolds via one constant so the
# build location and the restore location can never drift apart.
_VENV_DIR = DEFAULT_VENV_RESTORE_DIR


def _bindings(context: DecisionContext) -> tuple[ProjectRootBinding, RequirementsProjectBinding]:
    root = context.binding("project_root")
    requirements = context.binding("requirements_project")
    if not isinstance(root, ProjectRootBinding) or not isinstance(requirements, RequirementsProjectBinding):
        raise ValueError("pip_venv_build_v1 renderer reached without project_root and requirements bindings")
    return root, requirements


class PipVenvBuildRenderer:
    code = "pip_venv_build_v1"
    requires: frozenset[BindingKind] = frozenset({"project_root", "requirements_project"})

    def render(self, context: DecisionContext, target: ScriptTarget) -> RenderedScript:
        root, requirements = _bindings(context)
        runtime_artifact = runtime_artifact_path(root.path, VENV_RUNTIME_ARTIFACT_SUFFIX)

        body = _render_body(
            requirements_path=requirements.requirements_path,
            runtime_artifact=runtime_artifact,
            digest=requirements.digest,
        )

        dependencies = [
            CandidateDependency(
                kind="source",
                path=requirements.requirements_path,
                digest=requirements.digest,
                role="requirements",
            )
        ]
        evidence = [
            InferenceEvidence(
                code="single_root_requirements",
                path=requirements.requirements_path,
                digest=requirements.digest,
                detail="Exactly one requirements.txt at the logical project root.",
            )
        ]
        warnings = [
            make_warning("execution_not_validated"),
            make_warning("pip_environment_strategy"),
            make_warning("python_version_unknown"),
            make_warning("dependencies_not_locked", affected_paths=[requirements.requirements_path]),
        ]
        return RenderedScript(body=body, dependencies=dependencies, evidence=evidence, warnings=warnings)


def _render_body(
    *,
    requirements_path: str,
    runtime_artifact: str,
    digest: str,
) -> str:
    return f"""#!/usr/bin/env sh
set -eu

# Generated by repo2ree.
#
# Inference rule: root-pip-requirements-v1
# Evidence:
#   requirements.txt {sh_comment(digest)}
#
# Builds the environment with pip alone — no container — and packs the virtual
# environment as the runtime artifact. The venv is built outside the workspace
# (it is snapshot-hashed on every change) and bakes absolute paths, so runnables
# restore it to the same location.
#
# This script has been inferred but not yet validated by execution.

REQUIREMENTS={sh_quote(requirements_path)}
RUNTIME_ARTIFACT={sh_quote(runtime_artifact)}
VENV_DIR={sh_quote(_VENV_DIR)}

python -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --no-cache-dir --requirement "$REQUIREMENTS"

mkdir -p "$(dirname "$RUNTIME_ARTIFACT")"
tar -czf "$RUNTIME_ARTIFACT" -C "$(dirname "$VENV_DIR")" "$(basename "$VENV_DIR")"
"""
