export const ACTION_TYPES = {
  appShell: {
    setRee: "appShell/setRee",
    setReeSpec: "appShell/setReeSpec",
    setLocked: "appShell/setLocked",
    setRepoMode: "appShell/setRepoMode",
    setWorkspaceSourceState: "appShell/setWorkspaceSourceState",
    setArtifactStatus: "appShell/setArtifactStatus",
    setActionStates: "appShell/setActionStates",
    setBadges: "appShell/setBadges",
    setTimestamps: "appShell/setTimestamps",
    setWorkflowLogs: "appShell/setWorkflowLogs",
    setWorkflowParams: "appShell/setWorkflowParams",
    setEvaluationState: "appShell/setEvaluationState",
    setToast: "appShell/setToast",
    setPage: "appShell/setPage",
    setFocusedField: "appShell/setFocusedField",
    setNavCollapsed: "appShell/setNavCollapsed",
    setWorkspaceFiles: "appShell/setWorkspaceFiles",
    setReeArtifactFiles: "appShell/setReeArtifactFiles",
    hydrateWorkspace: "appShell/hydrateWorkspace",
    setSourceSnapshotFiles: "appShell/setSourceSnapshotFiles",
    setSourceSnapshotArchiveName: "appShell/setSourceSnapshotArchiveName",
    applySourceOutcome: "appShell/applySourceOutcome",
    setShowReviewPreview: "appShell/setShowReviewPreview",
    completeWorkflowRun: "appShell/completeWorkflowRun",
    resetWorkflowOnSourceChange: "appShell/resetWorkflowOnSourceChange",
  },
} as const;
