export const ACTION_TYPES = {
  appShell: {
    setReeSpec: "appShell/setReeSpec",
    setLocked: "appShell/setLocked",
    setRepoMode: "appShell/setRepoMode",
    setWorkspaceSourceState: "appShell/setWorkspaceSourceState",
    setArtifactStatus: "appShell/setArtifactStatus",
    setActionStates: "appShell/setActionStates",
    setBadges: "appShell/setBadges",
    setTimestamps: "appShell/setTimestamps",
    setWorkflowParams: "appShell/setWorkflowParams",
    setEvaluationState: "appShell/setEvaluationState",
    setActiveRunId: "appShell/setActiveRunId",
    setToast: "appShell/setToast",
    setPage: "appShell/setPage",
    setFocusedField: "appShell/setFocusedField",
    setNavCollapsed: "appShell/setNavCollapsed",
    setSourceSnapshotArchiveName: "appShell/setSourceSnapshotArchiveName",
    applySourceOutcome: "appShell/applySourceOutcome",
    setShowReviewPreview: "appShell/setShowReviewPreview",
    completeWorkflowRun: "appShell/completeWorkflowRun",
    resetWorkflowOnSourceChange: "appShell/resetWorkflowOnSourceChange",
  },
} as const;
