"""Fail-closed Docker activation scaffold.

The Docker load/run wrapper is mechanical once the runtime contract is known; the
activation *command* is not, so it is never selected automatically in Phase 1.
This renders the load/run plumbing around an empty ``set --`` the author fills,
with any image-declared commands offered as commented examples.
"""

from __future__ import annotations

from repo2ree_core.author_recipes.inference.models import (
    BindingKind,
    CandidateDependency,
    CommandCandidatesBinding,
    DecisionContext,
    DockerRuntimeContract,
    InferenceEvidence,
    RenderedScript,
    RuntimeContractBinding,
)
from repo2ree_core.author_recipes.inference.renderers._scaffold import (
    candidate_examples_block,
    sh_quote,
    unconfigured_guard,
)
from repo2ree_core.author_recipes.inference.warnings import make_warning
from repo2ree_core.author_recipes.targets import ScriptTarget


def _docker_contract(context: DecisionContext) -> tuple[DockerRuntimeContract, str]:
    binding = context.binding("runtime_contract")
    if not isinstance(binding, RuntimeContractBinding) or not isinstance(binding.contract, DockerRuntimeContract):
        raise ValueError("docker_activation_v1 renderer reached without a docker runtime_contract binding")
    return binding.contract, binding.provenance


class DockerActivationRenderer:
    code = "docker_activation_v1"
    requires: frozenset[BindingKind] = frozenset({"runtime_contract", "command_candidates"})

    def render(self, context: DecisionContext, target: ScriptTarget) -> RenderedScript:
        contract, provenance = _docker_contract(context)
        candidates_binding = context.binding("command_candidates")
        candidates = candidates_binding.candidates if isinstance(candidates_binding, CommandCandidatesBinding) else []

        body = _render_body(
            artifact_path=contract.artifact_path,
            image_ref=contract.image_ref,
            workspace_mount=contract.workspace_mount,
            working_directory=contract.working_directory,
            examples=candidate_examples_block(candidates, noun="activation"),
        )
        dependencies = [
            CandidateDependency(
                kind="runtime_artifact",
                path=contract.artifact_path,
                digest=context.runtime.accessor.stat(contract.artifact_path).digest or "",
                role="runtime",
            )
        ]
        evidence = [
            InferenceEvidence(
                code="docker_runtime_contract",
                path=contract.artifact_path,
                detail=f"Docker runtime {contract.image_ref} (provenance: {provenance}).",
            )
        ]
        warnings = [make_warning("execution_not_validated"), make_warning("activation_command_missing")]
        return RenderedScript(body=body, dependencies=dependencies, evidence=evidence, warnings=warnings)


def _render_body(
    *,
    artifact_path: str,
    image_ref: str,
    workspace_mount: str,
    working_directory: str,
    examples: str,
) -> str:
    guard = unconfigured_guard("Activation", "Edit the 'set --' line in this script before running activation.")
    return f"""#!/usr/bin/env sh
set -eu

# Generated by repo2ree.
#
# Inference rule: docker-runtime-activation-v1
# The Docker invocation was inferred. The activation command was not.
# Review and edit this script before running it.

RUNTIME_ARTIFACT={sh_quote(artifact_path)}
IMAGE_TAG={sh_quote(image_ref)}

# REQUIRED: define a finite command that proves the runtime is usable.
{examples}
set --

{guard}

docker load --input "$RUNTIME_ARTIFACT"

docker run --rm \\
    -v "$(pwd):{workspace_mount}" \\
    -w {sh_quote(working_directory)} \\
    "$IMAGE_TAG" \\
    "$@"
"""
