"""Shell renderer for the Docker build strategy.

Detection/planning (checks) and rendering are separate so ecosystem branches do
not each duplicate the shell wrapper. This renderer turns the resolved
``project_root`` + ``dockerfile`` bindings into the complete Docker build
script, copying every runtime constant it derives as an explicit literal — no
downstream consumer greps this shell for values.

The image reference is ``ree-runtime:<ree-name>`` — readable and stable for a
given REE — and the script carries no timestamp, so identical inputs render
byte-identical bytes.
"""

from __future__ import annotations

from repo2ree_core.author_recipes.inference.models import (
    BindingKind,
    CandidateDependency,
    DecisionContext,
    DockerfileBinding,
    InferenceEvidence,
    ProjectRootBinding,
    RenderedScript,
    ScriptTarget,
)
from repo2ree_core.author_recipes.inference.renderers._common import (
    DOCKER_RUNTIME_ARTIFACT_SUFFIX,
    runtime_artifact_path,
    runtime_image_ref,
    sh_comment,
    sh_quote,
)
from repo2ree_core.author_recipes.inference.warnings import make_warning


def _bindings(context: DecisionContext) -> tuple[ProjectRootBinding, DockerfileBinding]:
    root = context.binding("project_root")
    dockerfile = context.binding("dockerfile")
    # Guaranteed present by the DAG's binding-dataflow validation; this guard
    # turns a wiring bug into a clear error rather than an AttributeError.
    if not isinstance(root, ProjectRootBinding) or not isinstance(dockerfile, DockerfileBinding):
        raise ValueError("docker_build_v1 renderer reached without project_root and dockerfile bindings")
    return root, dockerfile


class DockerBuildRenderer:
    code = "docker_build_v1"
    requires: frozenset[BindingKind] = frozenset({"project_root", "dockerfile"})

    def render(self, context: DecisionContext, target: ScriptTarget) -> RenderedScript:
        root, dockerfile = _bindings(context)
        runtime_artifact = runtime_artifact_path(root.path, DOCKER_RUNTIME_ARTIFACT_SUFFIX)
        image_tag = runtime_image_ref(context.ree_name)
        body = _render_body(
            dockerfile_path=dockerfile.path,
            build_context=dockerfile.build_context,
            image_tag=image_tag,
            runtime_artifact=runtime_artifact,
            digest=dockerfile.digest,
            logical_root=root.path,
        )

        dependencies = [
            CandidateDependency(
                kind="source",
                path=dockerfile.path,
                digest=dockerfile.digest,
                role="dockerfile",
            )
        ]
        evidence = [
            InferenceEvidence(
                code="single_project_root_dockerfile",
                path=dockerfile.path,
                digest=dockerfile.digest,
                detail="Exactly one Dockerfile at the logical project root; build context is that root.",
            )
        ]
        warnings = [make_warning("execution_not_validated")]
        return RenderedScript(
            body=body,
            dependencies=dependencies,
            evidence=evidence,
            warnings=warnings,
        )


def _render_body(
    *,
    dockerfile_path: str,
    build_context: str,
    image_tag: str,
    runtime_artifact: str,
    digest: str,
    logical_root: str,
) -> str:
    return f"""#!/usr/bin/env sh
set -eu

# Generated by repo2ree.
#
# Inference rule: single-project-root-dockerfile-v1
# Evidence:
#   Dockerfile {sh_comment(digest)}
#   Logical project root: {sh_comment(logical_root)}
#   Exactly one Dockerfile at the logical project root
#   Build context resolved to the logical project root
#
# This script has been inferred but not yet validated by execution.

DOCKERFILE={sh_quote(dockerfile_path)}
BUILD_CONTEXT={sh_quote(build_context)}
IMAGE_TAG={sh_quote(image_tag)}
RUNTIME_ARTIFACT={sh_quote(runtime_artifact)}

docker build \\
    --file "$DOCKERFILE" \\
    --tag "$IMAGE_TAG" \\
    "$BUILD_CONTEXT"

mkdir -p "$(dirname "$RUNTIME_ARTIFACT")"
docker save \\
    "$IMAGE_TAG" \\
    --output "$RUNTIME_ARTIFACT"
"""
