"""Fail-closed venv activation scaffold.

For a packed-venv runtime the environment is a restored virtualenv rather than a
container: unpack the venv tarball to the absolute directory it was built at
(a venv bakes absolute paths), put its ``bin`` on ``PATH``, and run the
author-supplied command. Like the Docker scaffold the command itself is never
inferred in Phase 1.
"""

from __future__ import annotations

from repo2ree_core.author_recipes.inference.models import (
    BindingKind,
    CandidateDependency,
    DecisionContext,
    InferenceEvidence,
    RenderedScript,
    RuntimeContractBinding,
    ScriptTarget,
    VenvRuntimeContract,
)
from repo2ree_core.author_recipes.inference.renderers._scaffold import (
    candidate_examples_block,
    sh_quote,
    unconfigured_guard,
)
from repo2ree_core.author_recipes.inference.warnings import make_warning


def _venv_contract(context: DecisionContext) -> tuple[VenvRuntimeContract, str]:
    binding = context.binding("runtime_contract")
    if not isinstance(binding, RuntimeContractBinding) or not isinstance(binding.contract, VenvRuntimeContract):
        raise ValueError("venv_activation_v1 renderer reached without a venv runtime_contract binding")
    return binding.contract, binding.provenance


class VenvActivationRenderer:
    code = "venv_activation_v1"
    requires: frozenset[BindingKind] = frozenset({"runtime_contract"})

    def render(self, context: DecisionContext, target: ScriptTarget) -> RenderedScript:
        contract, provenance = _venv_contract(context)
        body = _render_body(
            artifact_path=contract.artifact_path,
            venv_restore_dir=contract.venv_restore_dir,
            examples=candidate_examples_block([], noun="activation"),
        )
        dependencies = [
            CandidateDependency(
                kind="runtime_artifact",
                path=contract.artifact_path,
                digest=context.runtime.accessor.stat(contract.artifact_path).digest or "",
                role="runtime",
            )
        ]
        evidence = [
            InferenceEvidence(
                code="venv_runtime_contract",
                path=contract.artifact_path,
                detail=f"Packed venv runtime (provenance: {provenance}).",
            )
        ]
        warnings = [make_warning("execution_not_validated"), make_warning("activation_command_missing")]
        return RenderedScript(body=body, dependencies=dependencies, evidence=evidence, warnings=warnings)


def _render_body(*, artifact_path: str, venv_restore_dir: str, examples: str) -> str:
    guard = unconfigured_guard("Activation", "Edit the 'set --' line in this script before running activation.")
    return f"""#!/usr/bin/env sh
set -eu

# Generated by repo2ree.
#
# Inference rule: venv-runtime-activation-v1
# The venv restore/run wrapper was inferred. The activation command was not.
# Review and edit this script before running it.

RUNTIME_ARTIFACT={sh_quote(artifact_path)}
VENV_DIR={sh_quote(venv_restore_dir)}

# REQUIRED: define a finite command that proves the runtime is usable.
{examples}
set --

{guard}

# Restore the packed virtual environment to the absolute path it was built at.
rm -rf "$VENV_DIR"
mkdir -p "$(dirname "$VENV_DIR")"
tar -xzf "$RUNTIME_ARTIFACT" -C "$(dirname "$VENV_DIR")"

PATH="$VENV_DIR/bin:$PATH"
export PATH
"$@"
"""
