import type { ArchiveRepo } from "../../application/workflow/WorkflowStepTypes";

export const ARCHIVE_REPOS: ArchiveRepo[] = [
  {
    key: "swh",
    label: "Software Heritage",
    shortLabel: "Sftw. Heritage",
    color: "#e4572e",
    bg: "#fff7f5",
    border: "#fbd0c4",
    url: "https://www.softwareheritage.org",
    desc: "Universal source code archive. Assigns a permanent SWHID intrinsic identifier tied to the exact content of your code.",
    idLabel: "SWHID",
    idField: "swhid",
    idPlaceholder: "swh:1:dir:…",
    params: [
      {
        key: "visit_type",
        label: "Visit type",
        type: "select",
        default: "git",
        options: ["git", "svn", "hg", "tar"],
        hint: "Repository type for the deposit",
      },
      {
        key: "metadata_only",
        label: "Metadata only",
        type: "bool",
        default: false,
        hint: "Only update metadata, skip re-archival if already present",
      },
    ],
    requires: [{ field: "_sourceAvailable", label: "Source available" }],
  },
  {
    key: "zenodo",
    label: "Zenodo",
    shortLabel: "Zenodo",
    color: "#1d6fa4",
    bg: "#f0f7ff",
    border: "#bfdbfe",
    url: "https://zenodo.org",
    desc: "CERN / OpenAIRE general-purpose research repository. Issues a citable DOI and supports versioning of datasets and software.",
    idLabel: "DOI",
    idField: "zenodo_doi",
    idPlaceholder: "10.5281/zenodo.xxxxxxx",
    params: [
      {
        key: "access",
        label: "Access",
        type: "select",
        default: "open",
        options: ["open", "embargoed", "restricted", "closed"],
        hint: "Access level for the deposit",
      },
      {
        key: "community",
        label: "Community",
        type: "text",
        default: "",
        hint: "Zenodo community slug to submit to (optional)",
      },
    ],
    requires: [
      { field: "name", label: "Name" },
      { field: "sbom", label: "SBOM" },
    ],
  },
  {
    key: "dataverse",
    label: "Dataverse",
    shortLabel: "Dataverse",
    color: "#5e4fa2",
    bg: "#f5f3ff",
    border: "#ddd6fe",
    url: "https://dataverse.org",
    desc: "Open-source research data repository platform. Widely used by universities and research institutions for FAIR data sharing.",
    idLabel: "Handle / DOI",
    idField: "dataverse_doi",
    idPlaceholder: "https://doi.org/10.7910/DVN/…",
    params: [
      {
        key: "server",
        label: "Server URL",
        type: "text",
        default: "https://dataverse.harvard.edu",
        hint: "Dataverse installation to deposit to",
      },
      {
        key: "dataverse",
        label: "Dataverse",
        type: "text",
        default: "root",
        hint: "Target dataverse collection",
      },
    ],
    requires: [{ field: "name", label: "Name" }],
  },
];
