"""The baked-in, project-free reproducer shipped inside every REE bundle.

Code Ocean capsules ship a ``run`` master script and a ``REPRODUCING.md`` so a
download is reproducible on its own. This module is the repo2ree equivalent: it
generates the top-level ``run.sh`` and ``REPRODUCING.md`` entries that turn the
otherwise-inert bundle (``ree/ree.json`` + ``ree/snapshot.tar.gz`` +
``ree/overlay/`` + ``ree/artifacts/``) into something a user can run with no
repo2ree install — the same lifecycle the workbench runs, reimplemented as
portable POSIX shell.

The generated ``run.sh`` exposes the shared :mod:`repo2ree_core.reproduction`
verbs so its ``--help`` mirrors the executor CLI:

* ``acquire-source`` — extract the bundled snapshot, or (sourceless bundle)
  fetch from the origin and verify against the recorded SWHID. Verification is
  best-effort: a local machine may not have the ``swh`` tool, so a missing tool
  (or a mismatch) **warns** rather than failing — the fetch still happens;
* ``materialize-workspace`` — assemble a clean ``ree/workspace/`` = the acquired
  source overlaid with the author scripts (overlay wins), re-restoring the
  sealed runtime from ``ree/artifacts/`` (a cheap copy, never a rebuild). This
  resets state so each run starts from a deterministic slate;
* ``build-runtime`` / ``test-activation`` / ``experiment <name>`` — run the
  author scripts from the workspace root, reusing the sealed runtime when
  present and otherwise building it once.

Plus two bundle-only orchestration helpers: ``all`` (the whole pipeline against
a single workspace) and ``list``.

Pure module: it builds bytes from values and performs no filesystem I/O. The
generated bytes are deterministic given their inputs, so the bundle stays
content-addressable for seal hashing.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import PurePosixPath

from repo2ree_core.reproduction import (
    ACQUIRE_SOURCE,
    BUILD_RUNTIME,
    EXPERIMENT,
    MATERIALIZE_WORKSPACE,
    REPRODUCTION_COMMANDS,
    TEST_ACTIVATION,
)
from repo2ree_core.reserved_paths import RESERVED_ACTIVATION_SCRIPT, RESERVED_BUILD_SCRIPT

# Top-level bundle entries (siblings of ``ree/``).
REPRODUCER_SCRIPT_ENTRY_PATH = "run.sh"
REPRODUCER_README_ENTRY_PATH = "REPRODUCING.md"

# The reproducer registry is tab-delimited. Experiment names are constrained by
# EXPERIMENT_NAME_PATTERN (letters, digits, space, '.', '_', '-') so they can
# never contain a tab or newline, keeping the line format unambiguous.
_FIELD_SEP = "\t"

# Maps each reproduction verb to the run.sh function that implements it. The
# experiment verb is dispatched specially (it takes a name argument), so it is
# absent here.
_VERB_FUNCTIONS = {
    ACQUIRE_SOURCE.name: "do_acquire",
    MATERIALIZE_WORKSPACE.name: "do_materialize",
    BUILD_RUNTIME.name: "do_build",
    TEST_ACTIVATION.name: "do_activate",
}


def _shell_single_quote(value: str) -> str:
    """Quote ``value`` for safe inclusion inside POSIX single quotes."""
    return "'" + value.replace("'", "'\\''") + "'"


def _dispatch_arms() -> str:
    """Render the per-verb ``case`` arms from the shared command registry."""
    arms: list[str] = []
    for command in REPRODUCTION_COMMANDS:
        if command.name == EXPERIMENT.name:
            arms.append(f'  {command.name}) shift; do_experiment "${{1:-}}" ;;')
        else:
            arms.append(f"  {command.name}) {_VERB_FUNCTIONS[command.name]} ;;")
    return "\n".join(arms)


def _list_lines() -> str:
    """Render the ``list`` summaries from the shared command registry."""
    return "\n".join(f'  say "  {command.name:<24}{command.summary}"' for command in REPRODUCTION_COMMANDS)


def build_reproducer_sh(
    *,
    build_script: str,
    activation_script: str,
    experiments: Sequence[tuple[str, str]],
    runtime_workspace_path: str | None,
    runtime_artifact_basename: str | None,
    origin_url: str = "",
    source_type: str = "",
    swhid: str = "",
) -> bytes:
    """Render the self-contained ``run.sh`` for a bundle.

    ``experiments`` is a sequence of ``(name, run_script)`` pairs. The runtime
    arguments are non-empty together only when a built runtime was sealed into
    ``ree/artifacts/``; when either is missing the script builds instead of
    reusing. ``origin_url``/``source_type``/``swhid`` let a sourceless bundle
    re-fetch and best-effort verify its source.
    """
    experiment_lines = "".join(
        f"{name}{_FIELD_SEP}{run_script}\n" for name, run_script in experiments if name and run_script
    )
    header = "\n".join(
        (
            f"BUILD_SCRIPT={_shell_single_quote(build_script)}",
            f"ACTIVATION_SCRIPT={_shell_single_quote(activation_script)}",
            f"RUNTIME_WS_PATH={_shell_single_quote(runtime_workspace_path or '')}",
            f"RUNTIME_ARTIFACT={_shell_single_quote(runtime_artifact_basename or '')}",
            f"ORIGIN_URL={_shell_single_quote(origin_url or '')}",
            f"SOURCE_TYPE={_shell_single_quote(source_type or '')}",
            f"SWHID={_shell_single_quote(swhid or '')}",
        )
    )
    script = _RUN_SH_TEMPLATE.format(
        header=header,
        experiments=experiment_lines,
        dispatch=_dispatch_arms(),
        list_lines=_list_lines(),
    )
    return script.encode("utf-8")


def reproducer_entries(
    *,
    build_script: str = RESERVED_BUILD_SCRIPT,
    activation_script: str = RESERVED_ACTIVATION_SCRIPT,
    experiments: Sequence[tuple[str, str]] = (),
    runtime_workspace_path: str | None = None,
    runtime_artifact_basename: str | None = None,
    origin_url: str = "",
    source_type: str = "",
    swhid: str = "",
) -> list[tuple[str, bytes]]:
    """Return the ``(path, bytes)`` bundle entries for the reproducer."""
    run_sh = build_reproducer_sh(
        build_script=build_script or RESERVED_BUILD_SCRIPT,
        activation_script=activation_script or RESERVED_ACTIVATION_SCRIPT,
        experiments=experiments,
        runtime_workspace_path=runtime_workspace_path,
        runtime_artifact_basename=runtime_artifact_basename,
        origin_url=origin_url,
        source_type=source_type,
        swhid=swhid,
    )
    return [
        (REPRODUCER_SCRIPT_ENTRY_PATH, run_sh),
        (REPRODUCER_README_ENTRY_PATH, _REPRODUCING_MD.encode("utf-8")),
    ]


def runtime_artifact_basename_from_remap(
    runtime_workspace_path: str | None,
    manifest_remap: object,
) -> str | None:
    """Pull the bundled runtime's ``ree/artifacts/`` basename, if any.

    ``manifest_remap`` maps original workspace paths to ``artifacts/<basename>``
    for files lifted into the bundle's ``artifacts/`` directory. A runtime entry
    is present only when the runtime was sealed in (``runtime_included``); absent
    means the reproducer must rebuild.
    """
    if not runtime_workspace_path or not isinstance(manifest_remap, dict):
        return None
    remapped = manifest_remap.get(runtime_workspace_path)
    if not isinstance(remapped, str) or not remapped:
        return None
    return PurePosixPath(remapped).name or None


# The body is intentionally dependency-light POSIX ``sh``: ``tar`` (already
# required to read ``snapshot.tar.gz``) plus, only for a sourceless bundle, the
# fetch tool for its source type. ``{header}``, ``{experiments}``, ``{dispatch}``
# and ``{list_lines}`` are the interpolation points; literal braces are doubled
# so ``str.format`` leaves them intact.
_RUN_SH_TEMPLATE = """#!/bin/sh
# repo2ree reproducer — generated at seal time. Runs without a repo2ree install.
#
# Layout (siblings of this script):
#   ree/ree.json          the sealed manifest
#   ree/snapshot.tar.gz    frozen upstream source (omitted for a sourceless seal)
#   ree/overlay/           author scripts (build/activation/experiments)
#   ree/artifacts/         sealed build outputs (runtime, sbom, ...)
#   ree/upstream/          acquired source layer (created by acquire-source)
#   ree/workspace/         clean view = upstream + overlay (created by materialize)
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REE="$HERE/ree"
UPSTREAM="$REE/upstream"
WS="$REE/workspace"

# --- generated registry -----------------------------------------------------
{header}

experiments() {{
  cat <<'__R2R_EXPERIMENTS__'
{experiments}__R2R_EXPERIMENTS__
}}
# ----------------------------------------------------------------------------

say() {{ printf '%s\\n' "$*"; }}
die() {{ printf 'error: %s\\n' "$*" >&2; exit 1; }}

# Best-effort source-identity check. The fetch already happened; a local machine
# may lack the `swh` tool, so a missing tool — or a mismatch — only warns.
verify_swhid() {{
  dir=$1
  [ -n "$SWHID" ] || {{ say "No recorded SWHID; source identity not verified."; return 0; }}
  if command -v swh >/dev/null 2>&1; then
    actual=$(swh identify --no-filename "$dir" 2>/dev/null || true)
    if printf '%s' "$actual" | grep -qF "$SWHID"; then
      say "Source identity verified against SWHID."
    else
      say "WARNING: source SWHID mismatch (recorded $SWHID, got ${{actual:-none}}) — reproduction may differ."
    fi
  else
    say "WARNING: 'swh' not installed; fetched source but could not verify against $SWHID."
  fi
}}

fetch_source() {{
  dest=$1
  say "Fetching source from $ORIGIN_URL ($SOURCE_TYPE)"
  case "$SOURCE_TYPE" in
    git)
      command -v git >/dev/null 2>&1 || die "git is required to fetch this source"
      git clone --quiet "$ORIGIN_URL" "$dest" ;;
    tarball)
      command -v curl >/dev/null 2>&1 || die "curl is required to fetch this source"
      curl -fsSL "$ORIGIN_URL" | tar -xz -C "$dest" ;;
    zip)
      command -v curl >/dev/null 2>&1 || die "curl is required to fetch this source"
      command -v unzip >/dev/null 2>&1 || die "unzip is required to fetch this source"
      tmp=$(mktemp); curl -fsSL "$ORIGIN_URL" -o "$tmp"; unzip -q "$tmp" -d "$dest"; rm -f "$tmp" ;;
    *)
      die "cannot fetch source: unknown source_type '$SOURCE_TYPE'" ;;
  esac
}}

# Populate the upstream source layer once: extract the bundled snapshot, else
# fetch from the origin and verify. Idempotent — skips if already populated.
do_acquire() {{
  if [ -d "$UPSTREAM" ] && [ -n "$(ls -A "$UPSTREAM" 2>/dev/null)" ]; then
    return 0
  fi
  rm -rf "$UPSTREAM"; mkdir -p "$UPSTREAM"
  if [ -f "$REE/snapshot.tar.gz" ]; then
    tar -xzf "$REE/snapshot.tar.gz" -C "$UPSTREAM"
    say "Source: extracted bundled snapshot (identity sealed in)."
  elif [ -n "$ORIGIN_URL" ]; then
    fetch_source "$UPSTREAM"
    verify_swhid "$UPSTREAM"
  else
    say "WARNING: no bundled snapshot and no origin URL — assembling overlay-only workspace."
  fi
}}

# Re-restore the sealed runtime to its workspace path (a cheap copy). Returns
# non-zero when no runtime was sealed in, so callers can fall back to building.
restore_runtime() {{
  [ -n "$RUNTIME_WS_PATH" ] && [ -n "$RUNTIME_ARTIFACT" ] \\
    && [ -f "$REE/artifacts/$RUNTIME_ARTIFACT" ] || return 1
  dest="$WS/$RUNTIME_WS_PATH"
  mkdir -p "$(dirname -- "$dest")"
  cp "$REE/artifacts/$RUNTIME_ARTIFACT" "$dest"
}}

# Assemble a clean workspace = upstream + overlay (overlay wins), then re-restore
# the sealed runtime. Resets state so each run starts from a deterministic slate.
do_materialize() {{
  do_acquire
  rm -rf "$WS"; mkdir -p "$WS"
  if [ -n "$(ls -A "$UPSTREAM" 2>/dev/null)" ]; then
    ( cd "$UPSTREAM" && tar -cf - . ) | ( cd "$WS" && tar -xf - )
  fi
  if [ -d "$REE/overlay" ]; then
    ( cd "$REE/overlay" && tar -cf - . ) | ( cd "$WS" && tar -xf - )
  fi
  restore_runtime || true
  say "Materialized clean workspace at ree/workspace/"
}}

# Set up the workspace only if it is not already materialized (non-destructive),
# so running one verb after another does not silently reset state.
ensure_workspace() {{
  if [ ! -d "$WS" ] || [ -z "$(ls -A "$WS" 2>/dev/null)" ]; then
    do_materialize
  fi
}}

# Reuse the sealed runtime when present; otherwise build it once.
ensure_runtime() {{
  if restore_runtime; then
    say "Reusing sealed runtime -> $RUNTIME_WS_PATH (build skipped)"
  else
    do_build
  fi
}}

run_in_workspace() {{
  script=$1
  [ -f "$WS/$script" ] || die "script not found in workspace: $script"
  say "\\$ sh $script"
  ( cd "$WS" && sh "$script" )
}}

do_build() {{ ensure_workspace; say "== build-runtime =="; run_in_workspace "$BUILD_SCRIPT"; }}

do_activate() {{
  ensure_workspace; ensure_runtime
  say "== test-activation =="
  run_in_workspace "$ACTIVATION_SCRIPT"
}}

do_experiment() {{
  name=${{1:-}}
  [ -n "$name" ] || die "usage: $0 experiment <name>"
  script=$(experiments | while IFS='\t' read -r n s; do
    [ "$n" = "$name" ] && {{ printf '%s' "$s"; break; }}
  done)
  [ -n "$script" ] || die "no experiment named: $name (try '$0 list')"
  ensure_workspace; ensure_runtime
  say "== experiment: $name =="
  run_in_workspace "$script"
}}

# One-click: acquire -> materialize -> runtime -> activation -> every experiment.
# Runs against a single materialized workspace (experiments are not isolated from
# each other). Aborts on the first failure (set -e), including inside the loop.
do_all() {{
  do_materialize
  ensure_runtime
  say "== test-activation =="
  run_in_workspace "$ACTIVATION_SCRIPT"
  experiments | while IFS='\t' read -r n s; do
    [ -n "$n" ] || continue
    say "== experiment: $n =="
    run_in_workspace "$s"
  done
  say ""
  say "All steps completed."
}}

do_list() {{
  say "Reproduction commands:"
{list_lines}
  if experiments | grep -q .; then
    say ""
    say "Experiments:"
    experiments | while IFS='\t' read -r n s; do
      [ -n "$n" ] && say "  $n  ->  $s"
    done
  fi
  say ""
  say "Run everything end-to-end:  sh $0 all"
  say "Or one phase at a time, e.g.: sh $0 experiment <name>"
}}

case "${{1:-}}" in
  "")            do_materialize; say ""; do_list ;;
  all|reproduce) do_all ;;
{dispatch}
  list)          ensure_workspace; do_list ;;
  -h|--help|help) do_list ;;
  *)             die "unknown command: $1 (try '$0 list')" ;;
esac
"""


_REPRODUCING_MD = """# Reproducing this REE

This is a sealed **repo2ree** Reproducible Execution Environment (REE). It is
self-contained: you can reproduce it on your own machine without installing
repo2ree. Everything needed is in this archive.

## Prerequisites

- A POSIX shell and `tar` (present on macOS/Linux; on Windows use WSL or Git
  Bash).
- Whatever runtime the author's scripts call into — commonly **Docker**. Each
  run script fully owns how it executes (for example its own `docker run …`), so
  read `ree/overlay/` if you want to see exactly what will run.
- Only if the source was **not** bundled: the fetch tool for its type (`git`,
  `curl`, `unzip`) and, optionally, the `swh` CLI to verify source identity
  against the recorded SWHID. Without `swh` the source is still fetched; it just
  cannot be cryptographically verified.

## Layout

```
run.sh                 one-click entrypoint (this is what you run)
REPRODUCING.md         this file
ree/ree.json           the sealed manifest (name, experiments, outputs, …)
ree/snapshot.tar.gz    frozen upstream source (omitted for a sourceless seal)
ree/overlay/           author scripts (build / activation / experiments)
ree/artifacts/         sealed build outputs (runtime image, SBOM, …)
ree/workspace/         created by run.sh: upstream + overlay merged
```

## Run it

From the folder where you extracted this archive, the one-click path runs the
whole REE end-to-end against a single workspace — acquire, materialize, runtime,
activation, then every experiment in order:

```shell
sh run.sh all        # reproduce everything end-to-end (one click)
```

Or drive it one phase at a time:

```shell
sh run.sh                          # materialize a clean workspace and list commands
sh run.sh acquire-source           # extract/fetch the source (verify SWHID if able)
sh run.sh materialize-workspace    # assemble a clean workspace = source + overlay
sh run.sh build-runtime            # build the runtime from the author's build script
sh run.sh test-activation          # prove the runtime is inhabitable
sh run.sh experiment <name>        # run a named experiment
sh run.sh list                     # list commands again
```

`materialize-workspace` assembles `ree/workspace/` from the acquired source with
the author scripts overlaid on top, so each script runs from the workspace root
exactly as it did when the REE was authored. It resets the workspace, so a
re-run starts from a clean slate; the sealed runtime is re-restored from
`ree/artifacts/` (a copy, not a rebuild). When no runtime was sealed in,
`build-runtime` produces it.
"""
