export const ACTION_TYPES = {
  workspaceEditor: {
    setRee: "workspaceEditor/setRee",
    setLocked: "workspaceEditor/setLocked",
    setRepoMode: "workspaceEditor/setRepoMode",
    setActionStates: "workspaceEditor/setActionStates",
    setBadges: "workspaceEditor/setBadges",
    setTimestamps: "workspaceEditor/setTimestamps",
    setWorkflowLogs: "workspaceEditor/setWorkflowLogs",
    setWorkflowParams: "workspaceEditor/setWorkflowParams",
    setToast: "workspaceEditor/setToast",
    setPage: "workspaceEditor/setPage",
    setFocusedField: "workspaceEditor/setFocusedField",
    setNavCollapsed: "workspaceEditor/setNavCollapsed",
    setWorkspaceFiles: "workspaceEditor/setWorkspaceFiles",
    setReeArtifactFiles: "workspaceEditor/setReeArtifactFiles",
    hydrateWorkspace: "workspaceEditor/hydrateWorkspace",
    setSourceSnapshotFiles: "workspaceEditor/setSourceSnapshotFiles",
    setSourceSnapshotArchiveName: "workspaceEditor/setSourceSnapshotArchiveName",
    applySourcePatchOutcome: "workspaceEditor/applySourcePatchOutcome",
    setShowReviewPreview: "workspaceEditor/setShowReviewPreview",
    completeWorkflowRun: "workspaceEditor/completeWorkflowRun",
    resetWorkflowOnSourceChange: "workspaceEditor/resetWorkflowOnSourceChange",
  },
} as const;
