export const ACTION_TYPES = {
  workspaceEditor: {
    setRee: "workspaceEditor/setRee",
    setLocked: "workspaceEditor/setLocked",
    setRepoMode: "workspaceEditor/setRepoMode",
    setActionStates: "workspaceEditor/setActionStates",
    setBadges: "workspaceEditor/setBadges",
    setTimestamps: "workspaceEditor/setTimestamps",
    setServiceLogs: "workspaceEditor/setServiceLogs",
    setServiceParams: "workspaceEditor/setServiceParams",
    setToast: "workspaceEditor/setToast",
    setPage: "workspaceEditor/setPage",
    setFocusedField: "workspaceEditor/setFocusedField",
    setNavCollapsed: "workspaceEditor/setNavCollapsed",
    setVirtualFiles: "workspaceEditor/setVirtualFiles",
    setWorkspaceReeFiles: "workspaceEditor/setWorkspaceReeFiles",
    hydrateWorkspace: "workspaceEditor/hydrateWorkspace",
    setImmutableSourceSnapshotFiles: "workspaceEditor/setImmutableSourceSnapshotFiles",
    setImmutableSourceSnapshotArchiveName: "workspaceEditor/setImmutableSourceSnapshotArchiveName",
    applySourcePatchOutcome: "workspaceEditor/applySourcePatchOutcome",
    setShowReviewerPreview: "workspaceEditor/setShowReviewerPreview",
    completeWorkflowRun: "workspaceEditor/completeWorkflowRun",
    resetWorkflowOnSourceChange: "workspaceEditor/resetWorkflowOnSourceChange",
  },
} as const;
