import type { Level } from "./Level";

export const LEVELS: Level[] = [
  {
    n: 0,
    label: "None",
    color: "#94a3b8",
    bg: "#f1f5f9",
    ink: "#475569",
    short: "NONE",
    desc: "No reproducibility metadata at all.",
    problem: "No descriptions available.",
    fix: "Start by writing a README.",
  },
  {
    n: 1,
    label: "Natural Language",
    color: "#6366f1",
    bg: "#eef2ff",
    ink: "#3730a3",
    short: "NAT·LANG",
    desc: "Requirements described in a README only.",
    problem: "Likely imprecise and incomplete.",
    fix: "Create a formal dependency file (e.g. requirements.txt).",
  },
  {
    n: 2,
    label: "Manifest File",
    color: "#3b82f6",
    bg: "#eff6ff",
    ink: "#1d4ed8",
    short: "MANIFEST",
    desc: "A dependency manifest exists (e.g. requirements.txt).",
    problem: "Installs different versions on different days.",
    fix: "Pin required versions (e.g. pandas==2.1.0).",
  },
  {
    n: 3,
    label: "Top-level Pins",
    color: "#0ea5e9",
    bg: "#f0f9ff",
    ink: "#0369a1",
    short: "TOP·PINS",
    desc: "Top-level dependency versions are pinned.",
    problem: "Transitive dependencies still float.",
    fix: "Use a lockfile (e.g. poetry.lock).",
  },
  {
    n: 4,
    label: "Dependencies Locked",
    color: "#06b6d4",
    bg: "#ecfeff",
    ink: "#0e7490",
    short: "DEPS·LOCK",
    desc: "All dependencies fully locked via a lockfile.",
    problem: "No system deps (libblas, glibc, CUDA).",
    fix: "Add containers or VMs.",
  },
  {
    n: 5,
    label: "Container Env",
    color: "#14b8a6",
    bg: "#f0fdfa",
    ink: "#0f766e",
    short: "CONTAINER",
    desc: "A container image (e.g. Dockerfile) is provided.",
    problem: "Base image and apt-get are non-deterministic.",
    fix: "Use declarative specs (e.g. Nix).",
  },
  {
    n: 6,
    label: "Declarative System",
    color: "#10b981",
    bg: "#ecfdf5",
    ink: "#047857",
    short: "DECL·SYS",
    desc: "Full system environment declared declaratively (e.g. Nix).",
    problem: "Source code availability of packages.",
    fix: "Use long-term archives like Software Heritage.",
  },
  {
    n: 7,
    label: "Beyond",
    color: "#059669",
    bg: "#d1fae5",
    ink: "#065f46",
    short: "BEYOND",
    desc: "Long-term archive of packages, hardware env, and sources of non-determinism documented.",
    problem: null,
    fix: null,
  },
];
